services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=80"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:D1kdlomu+B3gVMuE7xYXGlYLrOAzBHvB1fuesoA/SSY=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://tu-subdominio.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tu-host-db (por ejemplo: render-mysql.internal o IP remota)
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: (tu contraseña)
