app = "tomatch-service-deploy"  # tu nombre real de app
[build]
  dockerfile = "Dockerfile"
[deploy]
  release_command = "php artisan migrate --force"
[http_service]
  internal_port = 8080
  processes = ["app"]
